package io.github.octcarp.sustech.cs209a.proj.crawler.importer

object KeywordPreset {
    private val errorMap = null


    val topicMap = mapOf(
        // generated by claude 3.5 sonnet

        "generics" to setOf(
            "generic", "type parameter", "type parameters", "type erasure",
            "<T>", "wildcard", "bounded", "extends", "super"
        ),

        "lambda" to setOf(
            "lambdas", "functional interface", "anonymous function",
            "closure", "arrow function", "->", "::", "method reference",
            "functional programming"
        ),

        "io" to setOf(
            "input", "output", "file", "reader", "writer", "stream",
            "buffer", "nio", "path", "files", "directory", "filesystem",
            "read", "write", "inputstream", "outputstream", "filewriter",
            "filereader", "bufferedreader", "bufferedwriter"
        ),

        "stream" to setOf(
            "streams", "pipeline", "map", "filter", "reduce", "collect",
            "flatmap", "parallel stream", "sequential", "intermediate operation",
            "terminal operation", "collector"
        ),

        "file" to setOf(
            "files", "directory", "folder", "path", "filepath", "file system",
            "read file", "write file", "delete file", "file permission",
            "file attribute", "file handling"
        ),

        "concurrency" to setOf(
            "thread", "multithreading", "parallel", "async", "synchronization",
            "synchronized", "lock", "mutex", "semaphore", "volatile",
            "atomic", "executor", "executorservice", "future", "completablefuture",
            "blocking queue", "thread pool", "race condition", "deadlock"
        ),

        "socket" to setOf(
            "sockets", "networking", "tcp", "udp", "server socket", "client socket",
            "connection", "port", "host", "ip", "protocol", "websocket",
            "network programming", "socket programming"
        ),

        "gui" to setOf(
            "swing", "javafx", "awt", "user interface", "ui", "interface",
            "window", "frame", "panel", "component", "layout", "event handling",
            "button", "label", "textfield", "form", "dialog", "menu"
        ),

        "reflection" to setOf(
            "reflect", "class", "method", "field", "constructor",
            "invoke", "dynamic proxy", "annotation", "metadata",
            "introspection", "getclass", "getmethod", "getfield"
        ),

        "spring" to setOf(
            "spring boot", "spring mvc", "spring cloud", "spring security",
            "spring data", "dependency injection", "di", "ioc", "bean",
            "autowired", "component", "service", "repository", "controller",
            "rest controller", "configuration"
        ),

        "testing" to setOf(
            "test", "junit", "mockito", "mock", "stub", "assertion",
            "unit test", "integration test", "tdd", "bdd",
            "verify", "assert", "testcase", "test suite"
        )
    )

    private val knownExceptions = setOf(
        // generated by claude 3.5 sonnet

        // Runtime Exceptions
        "NullPointerException",
        "ArrayIndexOutOfBoundsException",
        "IllegalArgumentException",
        "IllegalStateException",
        "ClassCastException",
        "NumberFormatException",
        "ArithmeticException",
        "IndexOutOfBoundsException",
        "UnsupportedOperationException",
        "ConcurrentModificationException",
        "NoSuchElementException",
        "StringIndexOutOfBoundsException",

        // Checked Exceptions
        "IOException",
        "SQLException",
        "FileNotFoundException",
        "ClassNotFoundException",
        "InterruptedException",
        "ParseException",
        "CloneNotSupportedException",
        "NoSuchMethodException",
        "NoSuchFieldException",
        "URISyntaxException",
        "MalformedURLException",
        "RemoteException",
        "TimeoutException",
        "ExecutionException",
        "ServletException",

        // Errors
        "OutOfMemoryError",
        "StackOverflowError",
        "NoClassDefFoundError",
        "UnsatisfiedLinkError",
        "ExceptionInInitializerError",
        "AssertionError",
        "LinkageError",
        "ThreadDeath",
        "VirtualMachineError",

//        // concurrency related exceptions
//        "InterruptedException",
//        "ExecutionException",
//        "TimeoutException",
//        "CompletionException",
//
//        // reflection related exceptions
//        "InvocationTargetException",
//        "IllegalAccessException",
//        "InstantiationException",
//
//        // Collection related exceptions
//        "EmptyStackException",
//        "NoSuchElementException",
//
//        // IO related exceptions
//        "EOFException",
//        "StreamCorruptedException",
//        "ObjectStreamException",
//        "InvalidClassException",
//        "NotSerializableException",
//        "SocketException",
//        "SocketTimeoutException",
//        "ProtocolException",
//        "UnknownHostException",
//
//        // xml related exceptions
//        "SAXException",
//        "ParserConfigurationException",
//        "TransformerException",
//
//        // security related exceptions
//        "SecurityException",
//        "AccessControlException",
//        "CertificateException",
//        "KeyStoreException",
//        "NoSuchAlgorithmException",
//
//        // database related exceptions
//        "SQLSyntaxErrorException",
//        "SQLTimeoutException",
//        "BatchUpdateException",
//        "DataException",
//        "TransactionException",
//
//        // Spring related exceptions
//        "BeansException",
//        "DataAccessException",
//        "TransactionException",
//        "DataIntegrityViolationException",
//
//        // 其他常见异常
//        "ValidationException",
//        "ConstraintViolationException",
//        "JMSException",
//        "MessagingException",
//        "AuthenticationException",
//        "AuthorizationException"
    )
}
