package io.github.octcarp.sustech.cs209a.proj.common

object KeywordPreset {
    private val errorMap = null

    val topicMap = mapOf(
        // generated by OpenAI's GPT-4

        "generics" to setOf(
            "generics", "generic", "type parameter", "type parameters", "type erasure",
            "<T>", "wildcard", "bounded", "extends", "super",
            "raw type", "covariant", "contravariant", "generic method",
            "generic class", "generic interface", "parameterized type",
            "type inference", "type bounds", "diamond operator", "type casting"
        ),
        "lambda" to setOf(
            "lambda", "lambdas", "functional interface", "anonymous function",
            "closure", "arrow function", "->", "::", "method reference",
            "functional programming", "bi-function", "consumer", "supplier",
            "predicate", "stream lambda", "lambda expression", "declarative style",
            "lambda syntax", "lambda scope", "high-order function"
        ),
        "io" to setOf(
            "io", "input", "output", "file", "reader", "writer", "stream",
            "buffer", "nio", "path", "files", "directory", "filesystem",
            "read", "write", "inputstream", "outputstream", "filewriter",
            "filereader", "bufferedreader", "bufferedwriter", "randomaccessfile",
            "filechannel", "java.nio", "charset", "pathmatcher", "filewatcher",
            "datastream", "objectstream", "datainput", "dataoutput",
            "java.io", "serialization", "file locking", "file system watcher"
        ),
        "stream" to setOf(
            "stream", "streams", "pipeline", "map", "filter", "reduce", "collect",
            "flatmap", "parallel stream", "sequential", "intermediate operation",
            "terminal operation", "collector", "groupingby", "joining", "partitioningby",
            "lazy evaluation", "infinite streams", "stream api", "sorted stream",
            "stream performance", "stream filter", "stream manipulation",
            "stream generation", "stream operations", "stream exception handling"
        ),
        "file" to setOf(
            "file", "files", "directory", "folder", "path", "filepath", "file system",
            "read file", "write file", "delete file", "file permission",
            "file attribute", "file handling", "file creation", "file copying",
            "file renaming", "file listing", "file deletion", "temporary file",
            "hidden file", "file metadata", "file explorer", "file I/O",
            "file compression", "file extraction", "zip file", "file encryption"
        ),
        "concurrency" to setOf(
            "concurrency", "thread", "multithreading", "parallel", "async", "synchronization",
            "synchronized", "lock", "mutex", "semaphore", "volatile",
            "atomic", "executor", "executorservice", "future", "completablefuture",
            "blocking queue", "thread pool", "race condition", "deadlock",
            "reentrantlock", "countdownlatch", "cyclicbarrier", "forkjoinpool",
            "phaser", "readwritelock", "concurrentmap", "concurrenthashmap",
            "threadlocal", "asynchronous", "callable", "runnable",
            "parallelism", "thread interruption", "thread lifecycle"
        ),
        "socket" to setOf(
            "socket", "sockets", "networking", "tcp", "udp", "server socket", "client socket",
            "connection", "port", "host", "ip", "protocol", "websocket",
            "network programming", "socket programming", "java.net", "socketchannel",
            "datagramsocket", "serversocketchannel", "nio socket", "socket timeout",
            "asynchronous socket", "socket connection", "socket stream",
            "http socket", "ssl socket", "socket buffer"
        ),
        "gui" to setOf(
            "gui", "swing", "javafx", "awt", "user interface", "ui", "interface",
            "window", "frame", "panel", "component", "layout", "event handling",
            "button", "label", "textfield", "form", "dialog", "menu",
            "canvas", "paint", "imageicon", "color", "graphics", "layout manager",
            "fxml", "scene", "stage", "javafx controller", "event listener",
            "animation", "drag-and-drop", "mouse event", "keyboard event",
            "ui responsiveness", "css styling", "ui threading", "ui toolkit"
        ),
        "reflection" to setOf(
            "reflection", "reflect", "class method", "field", "constructor",
            "invoke", "dynamic proxy", "annotation", "metadata",
            "introspection", "getclass", "getmethod", "getfield",
            "methodhandle", "methodtype", "proxy class", "custom annotations",
            "reflection performance", "runtime inspection", "classloader",
            "dynamic class", "runtime proxy", "reflection utilities"
        ),
        "spring" to setOf(
            "spring", "spring boot", "spring mvc", "spring cloud", "spring security",
            "spring data", "dependency injection", "di", "ioc", "bean",
            "autowired", "component", "service", "repository", "controller",
            "rest controller", "configuration", "spring batch", "spring kafka",
            "spring jpa", "spring websocket", "spring aop", "spring scheduler",
            "spring integration", "spring boot starter", "spring actuator",
            "spring rest", "spring application context", "spring properties",
            "spring validation", "spring caching", "spring boot test"
        ),
        "testing" to setOf(
            "testing", "test", "junit", "mockito", "mock", "stub", "assertion",
            "unit test", "integration test", "tdd", "bdd", "verify", "assert",
            "testcase", "test suite", "assertj", "testng", "code coverage",
            "mocking static", "mockito annotations", "parameterized tests",
            "hamcrest", "assume", "lifecycle methods", "test-driven development",
            "behavior-driven development", "mockito verify", "mocking final classes"
        ),
        "json" to setOf(
            "json", "jackson", "gson", "serialization", "deserialization",
            "json parsing", "json object", "json array", "json node",
            "json mapper", "json serializer", "json deserializer", "jsonpath",
            "java json", "jsonschema", "json processing", "json validation",
            "json formatting", "nested json", "json stream"
        ),
        "security" to setOf(
            "security", "encryption", "decryption", "ssl", "tls", "certificate",
            "keystore", "truststore", "secure socket", "cryptography",
            "hashing", "authentication", "authorization", "security exception",
            "java security", "java cryptography", "cipher", "signature",
            "message digest", "keypair", "keyfactory", "java jwt", "oauth",
            "spring security", "token-based authentication", "secure communication"
        ),
        "database" to setOf(
            "database", "jdbc", "hibernate", "jpa", "sql", "nosql", "mysql", "postgresql",
            "mongodb", "database connection", "entity", "session", "transaction",
            "sql query", "query optimization", "jdbc driver", "connection pooling",
            "orm", "resultset", "databasemetadata", "database migration",
            "database schema", "sql join", "sql injection", "database locking"
        ),
        "performance" to setOf(
            "performance", "optimization", "memory management", "gc", "garbage collection",
            "profiling", "benchmarking", "latency", "throughput",
            "java performance", "jvm tuning", "heap dump", "memory leak",
            "cpu usage", "java mission control", "flight recorder", "performance testing"
        )
    )


    private val knownExceptions = setOf(
        // generated by claude 3.5 sonnet

        // Runtime Exceptions
        "NullPointerException",
        "ArrayIndexOutOfBoundsException",
        "IllegalArgumentException",
        "IllegalStateException",
        "ClassCastException",
        "NumberFormatException",
        "ArithmeticException",
        "IndexOutOfBoundsException",
        "UnsupportedOperationException",
        "ConcurrentModificationException",
        "NoSuchElementException",
        "StringIndexOutOfBoundsException",

        // Checked Exceptions
        "IOException",
        "SQLException",
        "FileNotFoundException",
        "ClassNotFoundException",
        "InterruptedException",
        "ParseException",
        "CloneNotSupportedException",
        "NoSuchMethodException",
        "NoSuchFieldException",
        "URISyntaxException",
        "MalformedURLException",
        "RemoteException",
        "TimeoutException",
        "ExecutionException",
        "ServletException",

        // Errors
        "OutOfMemoryError",
        "StackOverflowError",
        "NoClassDefFoundError",
        "UnsatisfiedLinkError",
        "ExceptionInInitializerError",
        "AssertionError",
        "LinkageError",
        "ThreadDeath",
        "VirtualMachineError",

//        // concurrency related exceptions
//        "InterruptedException",
//        "ExecutionException",
//        "TimeoutException",
//        "CompletionException",
//
//        // reflection related exceptions
//        "InvocationTargetException",
//        "IllegalAccessException",
//        "InstantiationException",
//
//        // Collection related exceptions
//        "EmptyStackException",
//        "NoSuchElementException",
//
//        // IO related exceptions
//        "EOFException",
//        "StreamCorruptedException",
//        "ObjectStreamException",
//        "InvalidClassException",
//        "NotSerializableException",
//        "SocketException",
//        "SocketTimeoutException",
//        "ProtocolException",
//        "UnknownHostException",
//
//        // xml related exceptions
//        "SAXException",
//        "ParserConfigurationException",
//        "TransformerException",
//
//        // security related exceptions
//        "SecurityException",
//        "AccessControlException",
//        "CertificateException",
//        "KeyStoreException",
//        "NoSuchAlgorithmException",
//
//        // database related exceptions
//        "SQLSyntaxErrorException",
//        "SQLTimeoutException",
//        "BatchUpdateException",
//        "DataException",
//        "TransactionException",
//
//        // Spring related exceptions
//        "BeansException",
//        "DataAccessException",
//        "TransactionException",
//        "DataIntegrityViolationException",
//
//        "ValidationException",
//        "ConstraintViolationException",
//        "JMSException",
//        "MessagingException",
//        "AuthenticationException",
//        "AuthorizationException"
    )
}